//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingsman20.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suit()
        {
            this.OrderSuit = new HashSet<OrderSuit>();
        }
    
        public int ID { get; set; }
        public string SuitName { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<int> MaterialID { get; set; }
        public decimal Cost { get; set; }
        public string Description { get; set; }
        public Nullable<bool> InStock { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Material Material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderSuit> OrderSuit { get; set; }
    }
}
